name: CI - frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: pnpm/action-setup@v4    
        with:
          version: 9       
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'               

      - run: pnpm -v                 
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm test -- --ci --runInBand
      - run: pnpm build
